config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :pages, only: [:index]
  resources :clusters, only: [:index, :new, :create] do
    resources :starts, only: [:new, :create]
    resources :associations, only: [:index]

  end
  resources :starts, only: [:new, :create]
  resources :users, only: [:show]
  root "pages#index"
  #root "clusters#index"

  # Defines the root path route ("/")
  
end

app/models/cluster.rb
class Cluster < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :associations, dependent: :destroy
  has_many :starts, through: :associations

  validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/clusters_controller.rb
class ClustersController < ApplicationController
  before_action :set_cluster, only: %i[show edit update destroy]

  # GET /clusters or /clusters.json
  def index
    @clusters = Cluster.all.includes([:user])
  end

  # GET /clusters/1 or /clusters/1.json
  def show; end

  # GET /clusters/new
  def new
    @cluster = Cluster.new
  end

  # GET /clusters/1/edit
  def edit; end

  # POST /clusters or /clusters.json
  def create
    @cluster = Cluster.new(cluster_params)
    @cluster.user = current_user

    respond_to do |format|
      if @cluster.save
        format.html { redirect_to clusters_path, notice: 'Cluster was successfully created.' }
        format.json { render :show, status: :created, location: @cluster }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cluster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clusters/1 or /clusters/1.json
  def update
    respond_to do |format|
      if @cluster.update(cluster_params)
        format.html { redirect_to cluster_url(@cluster), notice: 'Cluster was successfully updated.' }
        format.json { render :show, status: :ok, location: @cluster }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cluster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clusters/1 or /clusters/1.json
  def destroy
    @cluster.destroy

    respond_to do |format|
      format.html { redirect_to clusters_url, notice: 'Cluster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cluster
    @cluster = Cluster.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def cluster_params
    params.require(:cluster).permit(:name, :icon)
  end
end

app/helpers/clusters_helper.rb
module ClustersHelper
end

app/views/clusters/_cluster.html.erb
<ul class="clusters-home">
<% @clusters.each do |cluster| %>
  <% if can? :manage, cluster %>
  <li>
    <div class="cluster-img">
      <%= image_tag cluster.icon, alt: 'icon' %>
    </div>
    <h2><%= link_to cluster.name, cluster_associations_path(cluster_id: cluster.id) %></h2>
    <p>Transactions: <%= cluster.starts.count || 0 %></p>
  </li>
  <% end %>  
<% end %>
</ul>

app/views/clusters/_form.html.erb
<%= form_with(model: cluster) do |form| %>
  <% if cluster.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cluster.errors.count, "error") %> prohibited this cluster from being saved:</h2>

      <ul>
        <% cluster.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="fieldN">
    <%= form.text_field :name, placeholder: "Name" %>
  </div>
  <br/>
  <div class="categorie-input-container" >
    <%= form.select :icon, [
       ["Investment", "investment.png"], ["Bills", "bills.png" ],
       ["Healthcare", "health.png"], ["Education", "education.png"],
       ["Transportation", "public-transport.png"], ["Travels/Trips", "travel.png"],
       ["Food, Snacks, Restaurants", "food.png"], ["Gym and Self-care", "gym.png"],
       ["Entertainment", "entertainment.png"], ["Beauty", "beauty.png"], ["Shopping", "shopping.png"],
       ["Emergencies", "emergency.png"]
       ] %>
  </div>
  <br/>
  <br/>
  <br/>
  <br/>
   <div class="add-t-container">
    <%= form.submit 'Save',  class: "add-transaction"%>
  </div>
<br/>
  <div>
    <%= link_to "Back to clusters", clusters_path %> 
  </div>

<% end %>

app/views/clusters/edit.html.erb
<h1>Editing cluster</h1>

<%= render "form", cluster: @cluster %>

<br>

<div>
  <%= link_to "Show this cluster", @cluster %> |
  <%= link_to "Back to clusters", clusters_path %>
</div>

app/views/clusters/index.html.erb
<div id="cluster-container">
  <%= render partial: '/clusters/cluster' %>
  <div class="add-category">
    <%= link_to 'ADD A NEW CATEGORY', new_cluster_path, class: 'add-category-a' %>
  </div>
</div>

app/views/clusters/new.html.erb
<div class="new-transaction">
  <h1>New cluster</h1>
  <br/>
  <%= render 'form', cluster: @cluster %>
</div>

app/views/clusters/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cluster %>

<div>
  <%= link_to "Edit this cluster", edit_cluster_path(@cluster) %> |
  <%= link_to "Back to clusters", clusters_path %>

  <%= button_to "Destroy this cluster", @cluster, method: :delete %>
</div>