config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :pages, only: [:index]
  resources :clusters, only: [:index, :new, :create] do
    resources :starts, only: [:new, :create]
    resources :associations, only: [:index]

  end
  resources :starts, only: [:new, :create]
  resources :users, only: [:show]
  root "pages#index"
  #root "clusters#index"

  # Defines the root path route ("/")
  
end

app/models/start.rb
class Start < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :associations, dependent: :destroy
  has_many :clusters, through: :associations

  validates :name, presence: true, length: { maximum: 50 }
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/controllers/starts_controller.rb
class StartsController < ApplicationController
  before_action :set_start, only: %i[show edit update destroy]

  # GET /starts or /starts.json
  def index
    # @starts = Start.all
    # @clusters = Cluster.all
    # Icomment below line to get the error
    @cluster_starts = Starts.all.order('starts.created_at DESC').includes[:user]
  end

  # GET /starts/1 or /starts/1.json
  def show; end

  # GET /starts/new
  def new
    @start = Start.new
  end

  # GET /starts/1/edit
  def edit; end

  # POST /starts or /starts.json
  def create
    @start = Start.new(start_params)
    @start.author_id = current_user.id

    respond_to do |format|
      if @start.save
        @start_category = Association.create(start_id: @start.id, cluster_id: cluster_params[:cluster_id])
        format.html do
          redirect_to cluster_associations_path(@start_category.cluster_id), notice: 'Charge was successfully created.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /starts/1 or /starts/1.json
  def destroy
    @start.destroy

    respond_to do |format|
      format.html { redirect_to starts_url, notice: 'Start was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_start
    @start = Start.find(params[:id])
  end

  def cluster_params
    params.require(:start).permit(:cluster_id)
  end

  # Only allow a list of trusted parameters through.
  def start_params
    params.require(:start).permit(:name, :amount)
  end
end

app/helpers/starts_helper.rb
module StartsHelper
end

app/views/starts/_form.html.erb
<%= form_with(model: start) do |form| %>
  <% if start.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(start.errors.count, "error") %> prohibited this start from being saved:</h2>

      <ul>
        <% start.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.text_field :name, placeholder: "Name" %>
  </div>

  <div class="field">
    <%= form.text_field :amount, placeholder: "Amount" %>
  </div>

  <div class="categorie-input-container">
    <%= form.select :cluster_id, Cluster.all.collect {|cluster| [cluster.name, cluster.id]},{include_blank: true}, :required => 'required', class:"form-select" %>
  </div>

  <div class="add-t-container">
    <%= form.submit 'SAVE', class:"add-transaction" %>
  </div>

  <div>
    <%= link_to "Back to charges", clusters_path %>
  </div>
<% end %>

app/views/starts/_start.html.erb
<div id="<%= dom_id start %>">
</div>

app/views/starts/edit.html.erb
<h1>Editing start</h1>

<%= render "form", start: @start %>

<br>

<div>
  <%= link_to "Show this start", @start %> |
  <%= link_to "Back to starts", starts_path %>
</div>

app/views/starts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Payments</h1>

<div id="starts">
  <% @starts.each do |start| %>
    <%= render start %>
    <%#<p>
      <%= link_to "Show this start", start >
    </p>%>
  <% end %>
</div>

<%= link_to "New start", new_start_path %>

app/views/starts/new.html.erb
<div class="new-transaction">
  <h1>New transaction</h1>

  <%= render 'form', start: @start %>
</div>

app/views/starts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @start %>

<div>
  <%= link_to "Edit this start", edit_start_path(@start) %> |
  <%= link_to "Back to starts", starts_path %>

  <%= button_to "Destroy this start", @start, method: :delete %>
</div>