config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :pages, only: [:index]
  resources :clusters, only: [:index, :new, :create] do
    resources :starts, only: [:new, :create]
    resources :associations, only: [:index]

  end
  resources :starts, only: [:new, :create]
  resources :users, only: [:show]
  root "pages#index"
  #root "clusters#index"

  # Defines the root path route ("/")
  
end

app/models/association.rb
class Association < ApplicationRecord
  belongs_to :start
  belongs_to :cluster
end

app/controllers/associations_controller.rb
class AssociationsController < ApplicationController
  def index
    @cluster = Cluster.find(params[:cluster_id])
    @starts = @cluster.associations.includes(:start).order('starts.created_at DESC').map(&:start)
  end
end

app/helpers/associations_helper.rb
module AssociationsHelper
end

app/views/associations/_association.html.erb
<div id="<%= dom_id association %>">
</div>

app/views/associations/_form.html.erb
<%= form_with(model: association) do |form| %>
  <% if association.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(association.errors.count, "error") %> prohibited this association from being saved:</h2>

      <ul>
        <% association.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/associations/edit.html.erb
<h1>Editing association</h1>

<%= render "form", association: @association %>

<br>

<div>
  <%= link_to "Show this association", @association %> |
  <%= link_to "Back to associations", associations_path %>
</div>

app/views/associations/index.html.erb
<div>
  <ul class="start-container cluster-container">
  <div class="cluster-transactions-header">
    <h2><%= @cluster.name %> <span><%= "Total $#{total_amount(@starts)}" %></span></h2>
  </div>

  <% if @starts.empty? %>
    <li>
      <h3>You do not have any registered charges yet</h3>
    </li>
  <% end %>
  <% @starts.each do |start| %>
    <% if can? :manage, Start %>
    <li>
      <div class="start-card">      
      <div class="start-image"]>
        <%= image_tag @cluster.icon %>
      </div>
      <div class="start-info">
        <h3><%= start.name %></h3>
        <h4><%= start.created_at %></h4>
      </div>
      </div>
      <p>
        <%= start.amount %>
      </p>
    </li>
    <% end %>
  <% end %>
  </ul>

  <div class="add-c-container">
    <%= link_to "Add a new transaction", new_start_path, class: "transaction-new-add-category" %>
  </div>
</div>

app/views/associations/new.html.erb
<h1>New association</h1>

<%= render "form", association: @association %>

<br>

<div>
  <%= link_to "Back to associations", associations_path %>
</div>

app/views/associations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @association %>

<div>
  <%= link_to "Edit this association", edit_association_path(@association) %> |
  <%= link_to "Back to associations", associations_path %>

  <%= button_to "Destroy this association", @association, method: :delete %>
</div>